import { StyleSheet } from 'react-native';

export const filtersModalStyles = StyleSheet.create({
  modalContainer: {
    width: '90%',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
    position: 'relative',
    flexShrink: 1,
    backgroundColor: undefined, // backgroundColor-t propsból add át
  },
  scrollContent: {
    width: '100%',
    alignItems: 'flex-start',
    paddingBottom: 160,
  },
  closeButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
    padding: 2,
  },
  title: {
    width: '100%',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'left',
  },
  filterLabel: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 8,
  },
  styleTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 24,
  },
  styleTag: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 8,
    marginRight: 8,
    minWidth: 60,
    minHeight: 28,
  },
  styleTagCheckbox: {
    width: 16,
    height: 16,
    borderWidth: 2,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  styleTagText: {
    marginLeft: 6,
    fontWeight: 'bold',
    fontSize: 13,
  },
  cityInput: {
    borderWidth: 2,
    marginBottom: 4,
    padding: 12,
    width: '100%',
    borderRadius: 12,
    fontSize: 16,
    fontWeight: '500',
  },
  citySuggestionsContainer: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    maxHeight: 140,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    backgroundColor: undefined, // backgroundColor-t propsból add át
  },
  citySuggestion: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderRadius: 12,
  },
  citySuggestionText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  actionsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 32,
  },
});
